databaseChangeLog:
  - changeSet:
      id: 1
      author: "Alfredo Miranda"
      changes:
        - createTable:
            tableName: authors
            remarks: "tables to store authors information"
            columns:
              - column:
                  name: author_id
                  type: bigserial
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_author_id
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: varchar(255)
                  constraints:
                    nullable: true
              - column:
                  name: created_at
                  type: timestamptz
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamptz
                  constraints:
                    nullable: false
              - column:
                  name: version
                  type: int4
                  constraints:
                    nullable: false